name: Sync with Upstream Repository

on:
  push:
    branches:
      - main
      - develop # 원본 레포지토리의 main과 develop 브랜치 push 시 동작
  schedule:
    - cron: "0 * * * *" # 매 시간마다 확인
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 포크 레포지토리 체크아웃
      - name: Checkout Fork Repository
        uses: actions/checkout@v3

      # 2. 원본(Upstream) 레포지토리 추가
      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/codeit-frontend-part3-team3/The-julge

      # 3. main 브랜치 동기화
      - name: Sync main branch
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch upstream main
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || git merge --strategy-option theirs upstream/main
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/swp91/The-julge-fork.git main --force

      # 4. develop 브랜치 동기화
      - name: Sync develop branch
        if: github.ref == 'refs/heads/develop'
        run: |
          git fetch upstream develop
          git checkout develop
          git merge upstream/develop --allow-unrelated-histories --no-edit || git merge --strategy-option theirs upstream/develop
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/swp91/The-julge-fork.git develop --force
